Refactor GitHub Actions workflow to streamline document handling and improve error handling during branch checkout

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,23 +42,14 @@ jobs:
                   git commit -m "Update Docs" || echo "No changes to commit"
                   git pull
                   git push || (echo "Failed to push changes" && exit 1)
-            - name: Move Docs
-              run: |
-                  mv data/docs/** .
             - name: Fetch gh-pages
               run: |
                   git config --global user.name "GitHub Actions"
                   git config --global user.email "actions@github.com"
                   git fetch
-            # - name: Download Resume
-            #   uses: robinraju/release-downloader@v1.11
-            #   with:
-            #       latest: true
-            #       fileName: "resume.pdf"
-            #       repository: "MH0386/MH0386"
+                  git checkout gh-pages || (echo "Failed to checkout gh-pages branch" && exit 1)
             - name: Commit and Push Resume
               run: |
-                  git add *.pdf
-                  git checkout gh-pages || (echo "Failed to checkout gh-pages branch" && exit 1)
+                  git add data/docs/
                   git commit -m "Update Docs" || echo "No changes to commit"
                   git push || (echo "Failed to push changes" && exit 1)
